const TEAMS_DB = [
    // ===================== LA LIGA =====================
    { id: "rma", name: "Real Madrid", league: "La Liga", country: "España", tier: 1, europeanCompetition: "Champions League" },
    { id: "bar", name: "FC Barcelona", league: "La Liga", country: "España", tier: 1, europeanCompetition: "Champions League" },
    { id: "atm", name: "Atlético de Madrid", league: "La Liga", country: "España", tier: 1, europeanCompetition: "Champions League" },
    { id: "ath", name: "Athletic Club", league: "La Liga", country: "España", tier: 2, europeanCompetition: "Europa League" },
    { id: "vil", name: "Villarreal CF", league: "La Liga", country: "España", tier: 2, europeanCompetition: "Champions League" },
    { id: "bet", name: "Real Betis", league: "La Liga", country: "España", tier: 2, europeanCompetition: "Europa League" },
    { id: "sev", name: "Sevilla FC", league: "La Liga", country: "España", tier: 2, europeanCompetition: null },
    { id: "soc", name: "Real Sociedad", league: "La Liga", country: "España", tier: 2, europeanCompetition: null },
    { id: "val", name: "Valencia CF", league: "La Liga", country: "España", tier: 3, europeanCompetition: null },
    { id: "cel", name: "RC Celta de Vigo", league: "La Liga", country: "España", tier: 3, europeanCompetition: null },
    { id: "osa", name: "CA Osasuna", league: "La Liga", country: "España", tier: 3, europeanCompetition: null },
    { id: "ray", name: "Rayo Vallecano", league: "La Liga", country: "España", tier: 3, europeanCompetition: null },
    { id: "get", name: "Getafe CF", league: "La Liga", country: "España", tier: 3, europeanCompetition: null },
    { id: "esp", name: "RCD Espanyol", league: "La Liga", country: "España", tier: 3, europeanCompetition: null },
    { id: "ala", name: "Deportivo Alavés", league: "La Liga", country: "España", tier: 4, europeanCompetition: null },
    { id: "eli", name: "Elche CF", league: "La Liga", country: "España", tier: 4, europeanCompetition: null },
    { id: "lev", name: "Levante UD", league: "La Liga", country: "España", tier: 4, europeanCompetition: null },
    { id: "mal", name: "Málaga CF", league: "La Liga", country: "España", tier: 4, europeanCompetition: null },
    { id: "dep", name: "RC Deportivo de La Coruña", league: "La Liga", country: "España", tier: 4, europeanCompetition: null },
    { id: "rac", name: "Real Racing Club de Santander", league: "La Liga", country: "España", tier: 4, europeanCompetition: null },

    // ===================== PREMIER LEAGUE =====================
    { id: "mci", name: "Manchester City", league: "Premier League", country: "Inglaterra", tier: 1, europeanCompetition: "Champions League" },
    { id: "liv", name: "Liverpool FC", league: "Premier League", country: "Inglaterra", tier: 1, europeanCompetition: "Champions League" },
    { id: "ars", name: "Arsenal FC", league: "Premier League", country: "Inglaterra", tier: 1, europeanCompetition: "Champions League" },
    { id: "uni", name: "Manchester United", league: "Premier League", country: "Inglaterra", tier: 1, europeanCompetition: null },
    { id: "che", name: "Chelsea FC", league: "Premier League", country: "Inglaterra", tier: 2, europeanCompetition: "Conference League" },
    { id: "tot", name: "Tottenham Hotspur", league: "Premier League", country: "Inglaterra", tier: 2, europeanCompetition: "Europa League" },
    { id: "new", name: "Newcastle United", league: "Premier League", country: "Inglaterra", tier: 2, europeanCompetition: "Champions League" },
    { id: "ast", name: "Aston Villa", league: "Premier League", country: "Inglaterra", tier: 2, europeanCompetition: "Europa League" },
    { id: "bri", name: "Brighton & Hove Albion", league: "Premier League", country: "Inglaterra", tier: 2, europeanCompetition: null },
    { id: "nfo", name: "Nottingham Forest", league: "Premier League", country: "Inglaterra", tier: 3, europeanCompetition: null },
    { id: "cry", name: "Crystal Palace", league: "Premier League", country: "Inglaterra", tier: 3, europeanCompetition: null },
    { id: "eve", name: "Everton FC", league: "Premier League", country: "Inglaterra", tier: 3, europeanCompetition: null },
    { id: "ful", name: "Fulham FC", league: "Premier League", country: "Inglaterra", tier: 3, europeanCompetition: null },
    { id: "bou", name: "AFC Bournemouth", league: "Premier League", country: "Inglaterra", tier: 3, europeanCompetition: null },
    { id: "brd", name: "Brentford FC", league: "Premier League", country: "Inglaterra", tier: 3, europeanCompetition: null },
    { id: "lee", name: "Leeds United", league: "Premier League", country: "Inglaterra", tier: 4, europeanCompetition: null },
    { id: "sun", name: "Sunderland AFC", league: "Premier League", country: "Inglaterra", tier: 4, europeanCompetition: null },
    { id: "ips", name: "Ipswich Town", league: "Premier League", country: "Inglaterra", tier: 4, europeanCompetition: null },
    { id: "hul", name: "Hull City", league: "Premier League", country: "Inglaterra", tier: 4, europeanCompetition: null },
    { id: "cov", name: "Coventry City", league: "Premier League", country: "Inglaterra", tier: 4, europeanCompetition: null },

    // ===================== SERIE A =====================
    { id: "int", name: "FC Internazionale", league: "Serie A", country: "Italia", tier: 1, europeanCompetition: "Champions League" },
    { id: "juv", name: "Juventus FC", league: "Serie A", country: "Italia", tier: 1, europeanCompetition: "Champions League" },
    { id: "mil", name: "AC Milan", league: "Serie A", country: "Italia", tier: 1, europeanCompetition: "Champions League" },
    { id: "nap", name: "SSC Napoli", league: "Serie A", country: "Italia", tier: 1, europeanCompetition: "Champions League" },
    { id: "ata", name: "Atalanta BC", league: "Serie A", country: "Italia", tier: 2, europeanCompetition: "Champions League" },
    { id: "rom", name: "AS Roma", league: "Serie A", country: "Italia", tier: 2, europeanCompetition: "Europa League" },
    { id: "laz", name: "SS Lazio", league: "Serie A", country: "Italia", tier: 2, europeanCompetition: null },
    { id: "bol", name: "Bologna FC", league: "Serie A", country: "Italia", tier: 2, europeanCompetition: null },
    { id: "fio", name: "Fiorentina", league: "Serie A", country: "Italia", tier: 2, europeanCompetition: null },
    { id: "tor", name: "Torino FC", league: "Serie A", country: "Italia", tier: 3, europeanCompetition: null },
    { id: "udi", name: "Udinese Calcio", league: "Serie A", country: "Italia", tier: 3, europeanCompetition: null },
    { id: "gen", name: "Genoa CFC", league: "Serie A", country: "Italia", tier: 3, europeanCompetition: null },
    { id: "lec", name: "Lecce", league: "Serie A", country: "Italia", tier: 3, europeanCompetition: null },
    { id: "cal", name: "Cagliari Calcio", league: "Serie A", country: "Italia", tier: 3, europeanCompetition: null },
    { id: "mza", name: "AC Monza", league: "Serie A", country: "Italia", tier: 3, europeanCompetition: null },
    { id: "com", name: "Como", league: "Serie A", country: "Italia", tier: 4, europeanCompetition: null },
    { id: "pca", name: "Parma Calcio", league: "Serie A", country: "Italia", tier: 4, europeanCompetition: null },
    { id: "sas", name: "Sassuolo Calcio", league: "Serie A", country: "Italia", tier: 4, europeanCompetition: null },
    { id: "ven", name: "Venezia", league: "Serie A", country: "Italia", tier: 4, europeanCompetition: null },
    { id: "fro", name: "Frosinone Calcio", league: "Serie A", country: "Italia", tier: 4, europeanCompetition: null },

    // ===================== BUNDESLIGA =====================
    { id: "bay", name: "Bayer 04 Leverkusen", league: "Bundesliga", country: "Alemania", tier: 1, europeanCompetition: "Champions League" },
    { id: "mun", name: "FC Bayern München", league: "Bundesliga", country: "Alemania", tier: 1, europeanCompetition: "Champions League" },
    { id: "dor", name: "Borussia Dortmund", league: "Bundesliga", country: "Alemania", tier: 1, europeanCompetition: "Champions League" },
    { id: "lei", name: "RB Leipzig", league: "Bundesliga", country: "Alemania", tier: 2, europeanCompetition: "Champions League" },
    { id: "stu", name: "Stuttgart", league: "Bundesliga", country: "Alemania", tier: 2, europeanCompetition: "Champions League" },
    { id: "fra", name: "Eintracht Frankfurt", league: "Bundesliga", country: "Alemania", tier: 2, europeanCompetition: "Europa League" },
    { id: "wol", name: "Wolfsburg", league: "Bundesliga", country: "Alemania", tier: 2, europeanCompetition: null },
    { id: "glb", name: "Borussia Mönchengladbach", league: "Bundesliga", country: "Alemania", tier: 2, europeanCompetition: null },
    { id: "bre", name: "Werder Bremen", league: "Bundesliga", country: "Alemania", tier: 3, europeanCompetition: null },
    { id: "mai", name: "Mainz 05", league: "Bundesliga", country: "Alemania", tier: 3, europeanCompetition: null },
    { id: "fre", name: "Freiburg", league: "Bundesliga", country: "Alemania", tier: 3, europeanCompetition: null },
    { id: "tsg", name: "Hoffenheim", league: "Bundesliga", country: "Alemania", tier: 3, europeanCompetition: null },
    { id: "aug", name: "Augsburgo", league: "Bundesliga", country: "Alemania", tier: 3, europeanCompetition: null },
    { id: "ham", name: "Hamburgo", league: "Bundesliga", country: "Alemania", tier: 4, europeanCompetition: null },
    { id: "elv", name: "Elversberg", league: "Bundesliga", country: "Alemania", tier: 4, europeanCompetition: null },
    { id: "kol", name: "FC Koln", league: "Bundesliga", country: "Alemania", tier: 4, europeanCompetition: null },
    { id: "sch", name: "Schalke 04", league: "Bundesliga", country: "Alemania", tier: 4, europeanCompetition: null },
    { id: "pad", name: "Paderborn", league: "Bundesliga", country: "Alemania", tier: 4, europeanCompetition: null },

    // ===================== LIGUE 1 =====================
    { id: "psg", name: "Paris Saint-Germain", league: "Ligue 1", country: "Francia", tier: 1, europeanCompetition: "Champions League" },
    { id: "mar", name: "Olympique de Marseille", league: "Ligue 1", country: "Francia", tier: 1, europeanCompetition: "Champions League" },
    { id: "mon", name: "AS Monaco", league: "Ligue 1", country: "Francia", tier: 2, europeanCompetition: "Champions League" },
    { id: "lyo", name: "Olympique Lyonnais", league: "Ligue 1", country: "Francia", tier: 2, europeanCompetition: "Europa League" },
    { id: "lil", name: "Lille OSC", league: "Ligue 1", country: "Francia", tier: 2, europeanCompetition: "Europa League" },
    { id: "len", name: "RC Lens", league: "Ligue 1", country: "Francia", tier: 2, europeanCompetition: "Europa League" },
    { id: "ren", name: "Stade Rennais", league: "Ligue 1", country: "Francia", tier: 2, europeanCompetition: null },
    { id: "nic", name: "OGC Nice", league: "Ligue 1", country: "Francia", tier: 2, europeanCompetition: null },
    { id: "stb", name: "Stade Brestois", league: "Ligue 1", country: "Francia", tier: 3, europeanCompetition: null },
    { id: "tou", name: "Toulouse FC", league: "Ligue 1", country: "Francia", tier: 3, europeanCompetition: null },
    { id: "par", name: "Paris FC", league: "Ligue 1", country: "Francia", tier: 3, europeanCompetition: null },
    { id: "str", name: "RC Strasbourg", league: "Ligue 1", country: "Francia", tier: 3, europeanCompetition: null },
    { id: "tro", name: "Troyes", league: "Ligue 1", country: "Francia", tier: 3, europeanCompetition: null },
    { id: "lem", name: "Le Mans", league: "Ligue 1", country: "Francia", tier: 3, europeanCompetition: null },
    { id: "hav", name: "Le Havre AC", league: "Ligue 1", country: "Francia", tier: 4, europeanCompetition: null },
    { id: "aue", name: "AJ Auxerre", league: "Ligue 1", country: "Francia", tier: 4, europeanCompetition: null },
    { id: "lor", name: "FC Lorient", league: "Ligue 1", country: "Francia", tier: 4, europeanCompetition: null },
    { id: "ang", name: "Angers SCO", league: "Ligue 1", country: "Francia", tier: 4, europeanCompetition: null }
];